nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.4.1.cjs

# npmRegistryServer: https://npm.pkg.github.com
# npmAlwaysAuth: true
npmRegistries:
  "https://npm.pkg.github.com":
    npmAlwaysAuth: true
npmScopes:
  wso2-enterprise:
    npmRegistryServer: https://npm.pkg.github.com
    npmAlwaysAuth: true
